#e This is a basic workflow to help you get started with Actions

name: 推送blog到vps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #list all files 
      - name: list all files
        run: ls -al
      # notice start job
      - name: start job
        run: echo "start sync blog code"
      # sync blog to vps
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzh
          path: blogs/
          remote_path: ${{ secrets.REMOTE_PATH_OF_BLOG }}
          remote_host: ${{ secrets.IP_ADDRESS_OF_BLOGHOST }}
          remote_port: ${{ secrets.PORT_OF_BLOGHOST }}
          remote_user: ${{ secrets.USER_OF_BLOGHOST }}
          remote_key:  ${{ secrets.BLOG_DEPLOY_KEY }}
